// "use client";

import "./globals.css";
import { ThemeContextProvider } from "../context/theme";
import { LoginModalContextProvider } from "../context/loginForm";
// import { AuthProvider } from "../context/auth";
import AuthProvider from "../components/authprovider/Authprovider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='fr'>
      <AuthProvider>
        <ThemeContextProvider>
          <LoginModalContextProvider>{children}</LoginModalContextProvider>
        </ThemeContextProvider>
      </AuthProvider>
    </html>
  );
}
