import "./globals.css";
import { ThemeContextProvider } from "./context/theme";
import Footer from "./components/footer/page";
import Header from "./components/header/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='fr'>
      <ThemeContextProvider>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeContextProvider>
    </html>
  );
}
